version: '3.3'
services:
    ignite-node-1:
        image: applem1support/ignite:2.12.0
        container_name: ignite-node-1
        ports:
            - "10800:10800"

    ignite-node-2:
        image: applem1support/ignite:2.12.0
        container_name: ignite-node-2
        ports:
            - "10900:10800"

    mysql:
        build: 
            context: mysql
            dockerfile: Dockerfile
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 'Kukusale8691!'
            MYSQL_DATABASE: 'best_server'
            MYSQL_USER: 'sqluser'
            MYSQL_PASSWORD: 'Kukusale8691!'
        ports:
            - 3306:3306
