version: '3.3'
services:
    zookeeper:
        image: zookeeper
        container_name: zookeeper
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_INIT_LIMIT: 5

    kafka-node-1:
        image: wurstmeister/kafka
        container_name: kafka-node-1
        ports:
            - "2181:2181"
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: localhost
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            ADVERTISED_PORT: 9092
            ADVERTISED_HOST_NAME: localhost
    mysql:
        build: 
            context: mysql
            dockerfile: Dockerfile
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 'Kukusale8691!'
            MYSQL_DATABASE: 'best_server'
            MYSQL_USER: 'sqluser'
            MYSQL_PASSWORD: 'Kukusale8691!'
        ports:
            - 3306:3306
